### ISSUE TITLE
My First Issue

### ISSUE THREAD

**Issue by googlebot-mountainview** [jayanthchandra/Codeathon#1]
Hi,

First Issue

![README.md](https://camo.githubusercontent.com/6753c8718d3767f2e9a0f52488d7375b9c18474c/687474703a2f2f6d656d652e6c6f71692e6d652f345676364b52445f2e6a7067)

[README.md](../blob/master/README.md)

**Comment by jayanthchandra** [comment]
Hi,

**This repository had to be deleted so thanks for posting a issue**. I suggest you to check out topcoder or Hackerearth codemonk  tutorials
